version: 2.1

orbs:
    circleci-cli: circleci/circleci-cli@0.1.9

jobs:
  trigger-build:
    executor: circleci/node:10.15.3
    steps:
      - checkout
      - circleci/setup-cli
      - run:
          name: Trigger build in another repository
          command: |
            circleci build dhanu0001//sfcc-cd-project-A \
            --branch Test-automation-builds \
            --revision <commit-hash> \
            --token "782ddf3c2db60b7ed64ac50489a16970899542c0"

workflows:
  version: 2
  build-and-trigger:
    jobs:
      - trigger-build:
          filters:
            branches:
              only: slack-notifications
