version: 2.1

orbs:
  trigger: circleci/trigger@1.5.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      # build and test your sample here
      - run: echo "test"

  trigger_build:
    executor: trigger/default
    steps:
      - trigger/build:
          organization: dhanu0001
          project: sfcc-cd-project-A
          branch: Test-automation-builds
          parameters:
            # add any required parameters for the triggered build

workflows:
  version: 2
  build-and-trigger:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - trigger_build:
          requires:
            - build
