version: 2.1
executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11-jdk

# Set parameter here
parameters:
  deploy_to_QA_Automation:
    type: boolean
    default: false

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - unless:
          condition: << pipeline.parameters.deploy_to_QA_Automation >> # by default this is triggered
          steps:
            - run: # build
  deploy_to_dev:
    executor: java-executor
    steps:
      - checkout
      - when:
         condition: << pipeline.parameters.deploy_to_QA_Automation >> # this would be triggered when you pass the parameter value via API
         steps:
           - run:
             command: |
               curl -u ${CIRCLECI_TOKEN}: -X POST --header "Content-Type: application/json" -d '{
               "parameters": {
               "deploy_to_dev": true
            }
         }' https://circleci.com/api/v2/project/${project_slug}/pipeline
             

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_to_dev
