version: 2.1

parameters:
  deploy_branch:
    type: string
    default: "Test-automation-builds"
  
# general:
#   branches:
#     only:
#       - Test-automation-builds
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      
      - run:
          name: Trigger the Build Job
          command: |
            printf "Triggering an "sfcc-cd-project" build on the Test-automation-builds branch\n\n"

            BUILD_INFO=$(curl -X POST -H -d \
                "{}" \
                "https://circleci.com/api/v1/project/dhanu0001/lambdatesh-circleci/tree/circleci-project-setup?circle-token=782ddf3c2db60b7ed64ac50489a16970899542c0")

            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \n https://circleci.com/gh/dhanu0001/lambdatesh-circleci/tree/circleci-project-setup"

workflows:
  build-and-trigger:
    jobs:
      - build
