version: 2.1
orbs:
  slack: circleci/slack@4.10.1

defaults: &defaults
  SOME_VARIABLE: "SFCC_CI_SETUP"

dev-env: &dev-env
  environment:
    <<: *defaults

parameters:
  deploy_branch:
    type: string
    default: "main"
  commit_message:
    type: string
    default: ""


jobs:
  setup-sfcc-cli:
    docker:
      - image: cimg/node:17.2.0
    resource_class: small
    environment:
      <<: *defaults
    steps:
      - checkout
      - run:
          name: install sfcc-ci
          command: |
            sudo npm install -g sfcc-ci
            sfcc-ci --version
      - run:
          name: authenticate sfcc-ci
          command: |
            sfcc-ci client:auth $CLIENT_ID $CLIENT_SECRET

      - run:
          name: Status of created sandbox by SFCC User
          command: |
            npx sfcc-ci sandbox:get --sandbox $SANDBOX_ID

      - run:
          name: test sfcc-ci
          command: |
            sfcc-ci sandbox:list

  test-hook:
    docker:
      - image: cimg/node:17.2.0
    resource_class: small
    environment:
      <<: *defaults
    steps:
      - when:
          condition:
            matches: { pattern: "^\\[ci\\].+$", value: << pipeline.parameters.commit_message >> }
          steps:
            - run:
                name: Test condition step
                command: |
                  echo "Should only run on commit with [ci] tag"


workflows:
  main-workflow:
    jobs:
      - setup-sfcc-cli:
          context:
            - slack-build-notification-secrets
          post-steps:
            - slack/notify:
                event: pass
                custom: |
                  {
                          "text": "CircleCI job succeeded!",
                          "blocks": [
                            {
                              "type": "header",
                              "text": {
                                "type": "plain_text",
                                "text": "Job Succeeded. :white_check_mark:",
                                "emoji": true
                              }
                            },
                            {
                              "type": "section",
                              "fields": [
                                {
                                  "type": "mrkdwn",
                                  "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                                },
                                        {
                                            "type": "mrkdwn",
                                            "text": "*Author*: $CIRCLE_USERNAME"
                                        },
                                        {
                                            "type": "mrkdwn",
                                            "text": "*Job Number*: $CIRCLE_BUILD_NUM"
                                        },
                                        {
                                            "type": "mrkdwn",
                                            "text": "*When*: $(date +'%m/%d/%Y %T')"
                                        },
                                        {
                                            "type": "mrkdwn",
                                            "text": "*Job Name*: $CIRCLE_JOB"
                                        },
                                        {
                                            "type": "mrkdwn",
                                            "text": "*Branch*: $CIRCLE_BRANCH"
                                        },
                                        {
                                            "type": "mrkdwn",
                                            "text": "*Commit-ID*: $CIRCLE_SHA1"
                                        },
                                        {
                                            "type": "mrkdwn",
                                            "text": "*Pull-Request*: $CI_PULL_REQUEST"
                                        }
                              ]
                            },
                            {
                                          "type": "section",
                                          "text": {
                                            "type": "mrkdwn",
                                            "text": "Kudos, Job ran successfully"
                                          }
                                        },
                            {
                              "type": "actions",
                              "elements": [
                                {
                                  "type": "button",
                                  "text": {
                                    "type": "plain_text",
                                    "text": "Visit Job"
                                  },
                                  "url": "${CIRCLE_BUILD_URL}"
                                }
                              ]
                            }
                          ]
                        }
              on_pull_requests: true
      - test-hook:
          filters:
            branches:
              only:
                - << pipeline.parameters.deploy_branch >>
          context:
            - slack-build-notification-secrets

